Algoritmo "teste"

Var
   user, password : caractere


Inicio
      escreva("Digite seu usuário: ")
      leia(user)
      escreva("Digite sua senha: ")
      leia(password)
      
      enquanto (user <> "admin")  ou (password <> "admin") faca
               escreva("Digite seu usuário: ")
               leia(user)
               escreva("Digite sua senha: ")
               leia(password)
      fimenquanto




Fimalgoritmo